---
- name: Instalador webserver
  hosts: webserver
  become: true
  tasks:
  - name: Instala Apache
    apt: name=apache2 update_cache=yes state=latest
  - name: Instala PHP
    apt:
      name: php 
      state: latest

- name: Instalador database
  hosts: database
  become: true
  tasks:
  - name: Instala Mysql
    apt:
      name: "{{item}}"
      state: present
    loop:
      - mysql-server
      - mysql-client 
      - python3-mysqldb
  - name: inicia el servicio mysql
    service:
      name: mysql
      state: started
      enabled: yes
  - name: crea un usuario
    mysql_user:
      name: user
      password: 123456789
      priv: '*.*:ALL'
      host: '%'
      state: present
  - name: creacion de la base de datos
    mysql_db:
      name: testdb
      state: present
  - name: Habilita el login remoto
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes
    notify:
      - Restart mysql
  handlers:
  - name: Restart mysql
    service:
      name: mysql
      state: restarted